framework:
    workflows:
        article_workflow:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Article
            initial_marking: draft
            places:
                - draft
                - reviewed
                - rejected
                - published
            transitions:
                to_review:
                    guard: "is_granted('ROLE_SPELLCHECKER')"
                    from: draft
                    to: reviewed
                publish:
                    guard: "is_granted('ROLE_ADMIN')"
                    from: reviewed
                    to: published
                reject:
                    guard: "is_granted('ROLE_ADMIN')"
                    from: reviewed
                    to: rejected
                to_draft:
                    guard: "is_granted('ROLE_WRITER')"
                    from: rejected
                    to: draft
